# Generated by Django 5.0 on 2024-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='diagram',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('Sentence Completion MCQ', 'Sentence Completion MCQ'), ('MCQ', 'MCQ'), ('Matching Heading', 'Matching Heading'), ('Matching Information', 'Matching Information'), ('True False', 'True False'), ('Yes No', 'Yes No'), ('Summary Completion', 'Summary Completion'), ('Diagram', 'Diagram')], max_length=30),
        ),
    ]
