# Generated by Django 5.0 on 2024-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testquestion_diagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='diagram',
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('Sentence Completion MCQ', 'Sentence Completion MCQ'), ('MCQ', 'MCQ'), ('Matching Heading', 'Matching Heading'), ('Matching Information', 'Matching Information'), ('True False', 'True False'), ('Yes No', 'Yes No'), ('Summary Completion', 'Summary Completion')], max_length=30),
        ),
    ]
