# Generated by Django 5.0 on 2024-06-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_testquestion_diagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='answer3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='diagram',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('Sentence Completion MCQ', 'Sentence Completion MCQ'), ('MCQ', 'MCQ'), ('Matching Heading', 'Matching Heading'), ('Matching Information', 'Matching Information'), ('True False', 'True False'), ('Yes No', 'Yes No'), ('Summary Completion', 'Summary Completion'), ('Diagram', 'Diagram')], max_length=30),
        ),
    ]
